# https://docs.redhat.com/ja/documentation/red_hat_build_of_keycloak/26.4/html-single/server_configuration_guide/index#all-config-

# Temporary admin account

bootstrap-admin-username=admin
bootstrap-admin-password=admin

# Database (set the same for JDBC_PING in cache-ispn.xml)

db=postgres
db-username=keycloak
db-password=password
db-url=jdbc:postgresql://localhost:5432/keycloak

# Features

health-enabled=true
metrics-enabled=true
#features-disabled=account-api,account2

# HTTPS

hostname=localhost
#https-port=18443
#https-certificate-file=${kc.home.dir}/conf/server.crt.pem
#https-certificate-key-file=${kc.home.dir}/conf/server.key.pem

# Clustering

#proxy-headers=xforwarded
spi-sticky-session-encoder-infinispan-should-attach-route=false

# Logging (with quarkus.properties)

log=console,file
log-file=${kc.home.dir}/data/log/keycloak.log

# Sizing

db-pool-max-size=100
http-pool-max-threads=100
#http-max-queued-requests=50
